version: '3.1'

services:
  idrac1:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=192.168.1.41
      - IDRAC_USER=root
      - IDRAC_PASSWORD=mason
    # Experimental! To directly mount an iso as iDRAC virtual media, 
    # uncomment the below and set to a filename that appears in /vmedia
      # - VIRTUAL_ISO=name_of_iso.iso
    volumes:
      - /path/to/app:/app
      - /path/to/media:/vmedia
      - /path/to/screenshots:/screenshots
  idrac2:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5801:5800
      - 5901:5900
    secrets:
      - idrac_host
      - idrac_user
      - idrac_password
    volumes:
      - /path/to/app:/app
      - /path/to/media:/vmedia
      - /path/to/screenshots:/screenshots
secrets:
  idrac_host:
    file: ./idrac_host.txt
  idrac_user:
    file: ./idrac_user.txt
  idrac_password:
    file: ./idrac_password.txt
